---
provisioner:
  name: ansible
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
  - name: ansible-role-java8-with-tag
    image: geerlingguy/docker-ubuntu2004-ansible

scenario:
  name: ubuntu-java8-with-tag

verifier:
  name: testinfra
  directory: ../tests/
