---
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
  - name: ansible-role-java8-with-tag
    image: geerlingguy/docker-ubuntu2004-ansible

playbooks:
  converge: playbook.yml

scenario:
  name: ubuntu-java8-with-tag

verifier:
  name: testinfra
  directory: ./tests/
