---
- name: assert JDK major version supported
  assert:
    that:
      - java_major_version in ('8', '11')

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ java_download_dir }}'

- name: set JDK version
  set_fact:
    java_jdk_version: "{{ java_full_version }}"

- name: Download JDK
  github_assets:
    repository: 'TravaOpenJDK/trava-jdk-{{ java_major_version }}-dcevm'
    tag: "{{ java_full_version if java_full_version != 8 and java_full_version != 11 else 'latest' | default('latest') }}"
    asset_pattern: '.*linux.*'
    download_path: "{{ java_download_dir }}"
  register: result

- name: Define java_home
  set_fact:
    java_home: "{{ java_install_dir }}/{{ result.meta.tag }}"

- name: create Java home directory
  become: yes
  file:
    path: '{{ java_home }}'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: install unarchive module dependencies (apt, yum, dnf, zypper)
  become: yes
  package:
    name:
      - tar
      - gzip
    state: present
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

- name: install JDK
  become: yes
  unarchive:
    remote_src: true
    src: "{{ java_download_dir }}/{{ result.meta.assets[0] }}"
    dest: '{{ java_home }}'
    extra_opts: [--strip-components=1]
    creates: '{{ java_home }}/bin/java'
    owner: root
    group: root
    mode: 'go-w'

- name: Set config
  include_tasks: write-environment-config.yml
