---
provisioner:
  name: ansible
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
  - name: ansible-role-default
    image: geerlingguy/docker-ubuntu2004-ansible

scenario:
  name: default

verifier:
  name: testinfra
  directory: tests
